(load "p30-even.scm")
(load "p38-sum.scm")
(define (simpson f a b n)
	(define h (/ (- b a) n))
	(define (y k)
			(f (+ a (* k h))))
	(define (factor k)
			(cond ((or (= k 0) (= k n))
					1)
					((even? k)
					2)
					(else
					4)))
	(define (term k)
			(* (factor k) (y k)))
	(define (next k)
			(+ k 1))
	(if (not (even? n))
		(display "n can't be odd")
		(* (/ h 3) (sum term 0 next n))))

